Re-manage example app proguard rules
Countly/countly-sdk-android pull request #224
Opened 2024-02-22 06:31 UTC by arifBurakDemiray

2024-02-23 11:13 UTC, turtledreams requested changes

2024-02-23 12:09 UTC, arifBurakDemiray commented on app/proguard-rules.pro
> -# Rules to keep the FCM dependency optional
I have not tried custom sound, sounds were working tough, let me get back when I try custom sounds

2024-02-26 06:57 UTC, arifBurakDemiray commented on app/proguard-rules.pro
> -# Rules to keep the FCM dependency optional
Okey, with custom sounds it works as expected.

2024-02-26 09:29 UTC, turtledreams approved these changes

2024-02-27 16:00 UTC, ijunaid approved these changes

2024-02-28 07:13 UTC, merged