Refactor upload symbols script
Countly/countly-sdk-android pull request #227
Opened 2024-03-08 08:10 UTC by arifBurakDemiray

2024-03-08 08:11 UTC, arifBurakDemiray commented on upload-plugin/src/main/groovy/ly/count/android/plugins/uploadSymbols.groovy
> +    project.tasks.register('uploadJavaSymbols') {
intellij suggested to use this because avoid unnecessary configuration

2024-03-08 08:13 UTC, arifBurakDemiray commented on upload-plugin/src/main/groovy/ly/count/android/plugins/uploadSymbols.groovy
> +        if (response.code() != 200) {
code is direct usage, use code()

2024-03-11 07:43 UTC, turtledreams requested changes
feel free too remove the commented out lines. instead just make sure that if we ask for this logs from a customer we should be able to pinpoint the issue.

Also there was this issue before(https://github.com/Countly/countly-sdk-android/issues/177) can you check any salvageable info we can add from that interaction to our docs.

2024-03-12 13:49 UTC, arifBurakDemiray commented
> feel free too remove the commented out lines. instead just make sure that if we ask for this logs from a customer we should be able to pinpoint the issue.
> 
> Also there was this issue before(#177) can you check any salvageable info we can add from that interaction to our docs.

We can add a doc entry about it. because his id of the plugin was wrong

We can add this for kotlin gradle entry
id 'ly.count.android.plugins.upload-symbols' version 'XX.XX.XX'

2024-03-13 19:46 UTC, merged