Extended crash filtering
Countly/countly-sdk-android pull request #229
Opened 2024-03-08 11:43 UTC by arifBurakDemiray

2024-03-08 11:56 UTC, ArtursKadikis requested changes
config option should be under "crashes" sub option.
depr call should name the replacement
no changelog entry

The crash filter should
return boolean and be able to change all fields

2024-03-11 15:10 UTC, ArtursKadikis requested changes
Add tests for "CrashData" for its changes and bit generation.

rework new config options to better ones

2024-03-11 15:10 UTC, ArtursKadikis commented on sdk/src/main/java/ly/count/android/sdk/CrashData.java
> +    private String stackTrace;
need "fatal" flag

2024-03-11 15:10 UTC, ArtursKadikis commented on sdk/src/main/java/ly/count/android/sdk/ModuleCrash.java
> +        if(globalCrashFilterCallback != null) {
move user filtering before SDK filtering

2024-03-11 15:10 UTC, ArtursKadikis commented on sdk/src/main/java/ly/count/android/sdk/CrashData.java
> +    private String stackTrace;
add crash metrics

2024-03-11 15:10 UTC, ArtursKadikis commented on sdk/src/main/java/ly/count/android/sdk/ModuleCrash.java
> +        }
if the crash data was modiffied, then in crash metrics we need to set a custom flag

2024-03-11 15:10 UTC, ArtursKadikis commented on sdk/src/main/java/ly/count/android/sdk/CrashData.java
> +    protected boolean crashChanged = false;
this needs to be per metric

2024-03-11 15:10 UTC, ArtursKadikis commented on sdk/src/main/java/ly/count/android/sdk/CrashData.java
> +}
this needs a protected "getChangedBits"

2024-03-12 06:32 UTC, arifBurakDemiray commented on sdk/src/main/java/ly/count/android/sdk/ConfigCrashes.java
> +    protected synchronized ConfigCrashes checkForNativeCrashDumps(boolean checkForDumps) {
it is true by default. So enable logic will not apply here. If I modify it, I must also modify a test

2024-03-12 10:35 UTC, arifBurakDemiray commented on sdk/src/main/java/ly/count/android/sdk/ConfigCrashes.java
> +    protected synchronized ConfigCrashes checkForNativeCrashDumps(boolean checkForDumps) {
will delete its editibility

2024-03-13 18:21 UTC, ArtursKadikis requested changes
Merge conflict.
Changelog needs to be updated

2024-03-25 13:15 UTC, ArtursKadikis requested changes

2024-03-25 13:15 UTC, ArtursKadikis commented on sdk/src/main/java/ly/count/android/sdk/CrashData.java
> +    protected String getChangedFieldsAsString() {
getChangedBitsAsInt

2024-03-27 11:23 UTC, ArtursKadikis requested changes
let us keep fatal

2024-03-27 11:23 UTC, ArtursKadikis commented on sdk/src/main/java/ly/count/android/sdk/CrashData.java
>      private final String[] checksums = new String[5];
let us leave a comment, what value should be in each index

2024-03-27 11:27 UTC, ArtursKadikis requested changes
Add tests

2024-04-03 09:00 UTC, merged