Internal Limits to Crashes
Countly/countly-sdk-android pull request #261
Opened 2024-04-02 08:43 UTC by arifBurakDemiray

ValuseSize, KeyLength, SegmentationValues

2024-04-15 11:28 UTC, AliRKat requested changes

2024-04-15 11:51 UTC, arifBurakDemiray commented on sdk/src/androidTest/java/ly/count/android/sdk/ModuleCrashTests.java
> +        CountlyConfig cConfig = (new CountlyConfig(ApplicationProvider.getApplicationContext(), "appkey", "http://test.count.ly")).setDeviceId("1234").setLoggingEnabled(true).enableCrashReporting();
I guess it tought it was for readiblit y maybe removed it

2024-04-15 12:27 UTC, AliRKat approved these changes

2024-04-16 07:55 UTC, turtledreams approved these changes
there is a typo on changelog, lets fix that later maybe with all changelog

2024-04-23 04:38 UTC, ArtursKadikis commented
@arifBurakDemiray conflict

2024-04-24 00:09 UTC, merged