Convert metric creation from JSON to Map
Countly/countly-sdk-android pull request #285
Opened 2024-04-22 13:14 UTC by arifBurakDemiray

2024-04-25 18:44 UTC, ArtursKadikis commented
waiting for @turtledreams

2024-04-26 04:54 UTC, turtledreams requested changes

2024-04-26 04:54 UTC, turtledreams commented on sdk/src/main/java/ly/count/android/sdk/DeviceInfo.java
> +    private void putIfNotNullEndNotEmpty(@NonNull Map<String, Object> metrics, String key, String value) {
possibly you meant 'putIfNotNull**A**ndNotEmpty'?

2024-04-26 04:54 UTC, turtledreams commented on sdk/src/main/java/ly/count/android/sdk/DeviceInfo.java
> +            if (metricOverride.containsKey("_device")) {
You did not want to log sth here?

2024-04-26 06:26 UTC, arifBurakDemiray commented on sdk/src/main/java/ly/count/android/sdk/DeviceInfo.java
> +            if (metricOverride.containsKey("_device")) {
added it for clarity

2024-04-26 08:54 UTC, turtledreams approved these changes

2024-04-26 11:39 UTC, merged