feat: new logs to the module consent
Countly/countly-sdk-android pull request #318
Opened 2024-05-21 08:13 UTC by arifBurakDemiray

2024-05-21 09:15 UTC, AliRKat approved these changes
nice work

2024-05-23 05:44 UTC, turtledreams requested changes

2024-05-23 05:44 UTC, turtledreams commented on sdk/src/main/java/ly/count/android/sdk/ModuleConsent.java
> +        L.d("[ModuleConsent] checkAllConsentInternal, Current consent state: " + sb);
can you wrap in []

2024-05-23 06:21 UTC, turtledreams approved these changes

2024-05-23 06:21 UTC, merged