[Android] move away from resuming
Countly/countly-sdk-android pull request #376
Opened 2024-08-08 11:41 UTC by arifBurakDemiray

2024-08-14 07:42 UTC, turtledreams requested changes
Looks good, lets add changelog entry 
In line 480 lets change to starting "stopped" ones instead, and in 487 "auto stopped" instead
and in docs lets mention we automatically stop/start views in bg/fg change. and again in docs for pause/resume lets mention that would only create and effect a single view by providing it accurate duration.

2024-08-16 05:45 UTC, ijunaid requested changes

2024-08-16 05:45 UTC, ijunaid commented on sdk/src/main/java/ly/count/android/sdk/ModuleViews.java
> +                startViewInternal(vd.viewName, vd.viewSegmentation, vd.isAutoStoppedView);
viewSegmentation is not needed here, its the segmentation provided after starting a view.

2024-08-21 13:40 UTC, turtledreams approved these changes

2024-08-22 06:53 UTC, merged